# Generated by Django 4.0.2 on 2022-05-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Phone', models.CharField(max_length=200, null=True)),
                ('Email', models.CharField(max_length=200, null=True)),
                ('Today', models.CharField(max_length=200, null=True)),
                ('State', models.CharField(max_length=200, null=True)),
                ('Places', models.CharField(max_length=200, null=True)),
                ('Date', models.CharField(max_length=200, null=True)),
                ('Enddate', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(max_length=200)),
                ('youremail', models.CharField(max_length=200)),
                ('yourphone', models.CharField(max_length=200)),
                ('yourproblem', models.CharField(max_length=200)),
            ],
        ),
    ]
